version: '3'
services:
  api_svc:
    build: 
      context: ../
      dockerfile: dev/Dockerfile
    container_name: auth_api
    image: auth_api_img
    networks:
      - auth_network
  mongodb_svc:
    container_name: auth_mongo
    image: mongo
    networks:
        - auth_network
    ports:
        - "27017:27017"
networks:
  auth_network: